title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          heroimage:
            type: files
            label: Hero Image
            multiple: false
            query: page.images.template('heroimage')
            uploads:
              template: heroimage
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

