title: Startseite

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          heroimage:
            type: files
            label: Headerbild
            required: true
            multiple: false
            query: page.images.template('article-heroimage')
            uploads:
              template: heroimage
          text:
            type: blocks
            fieldsets:
              - heading
              - text
              - list
              - image
              - code
              - person
              - youtube
              - horizontalcard
            label: Inhalt
            required: true
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        label: Seiten
        template: default
      files:
        type: files
