title: Startseite

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: blocks
            fieldsets:
              - fullbleed-text
              - verticalnewscardslider
              - logogrid
              - youtube
              - image
            label: Inhalt
            required: true
  sidebar:
    width: 1/3
    sections:
      fieldsRight:
        type: fields
        fields:
          heroimage:
            type: files
            label: Headerbild
            help: Das Bild wird auf die volle Bildschirmbreite des Besuchers skaliert. Damit es auch auf großen Monitoren gut aussieht bietet sich eine Breite von mindestens 2000 Pixeln an. Es sollte außerdem ein Seitenverhältnis von ca. 21:9 aufweisen. Eine gute Größe wäre zum Beispiel 2100x900 Pixel.
            required: true
            multiple: false
            query: page.images.template('article-heroimage')
            uploads:
              template: article-heroimage
          tag:
            type: tags
            max: 1
            label: Tag
      pages:
        type: pages
        label: Unterseiten
        templates:
          - default
          - article
          - horizontalcardlist
      files:
        type: files
