title: Site

tabs:
  content:
    label: Content
    icon: text
    sections:
      pages:
        type: pages
        info: "{{ page.slug }}"
        label: Seiten
        templates:
          - article
          - default
          - map
          - horizontalcardlist
          - category

  toolbar:
    label: Toolbar
    icon: wand
    sections:
      toolbarSection:
        type: fields
        fields:
          hideToolbar:
            label: Toolbar komplett verbergen?
            type: toggle
            text:
              - "Nein"
              - "Ja"

          toolbarElements:
            label: Toolbar Elemente
            type: structure
            help: Hier kannst du die Elemente in der Toolbar festlegen, die unterhalb des Hauptmenüs angezeigt wird.
            fields:
              title:
                label: Titel
                type: text
                required: true
              href:
                label: Linkziel
                type: pages
                required: true
                multiple: false
                max: 3
              icon:
                label: Icon
                type: select
                options: site.iconOptions
                help: Die Namen der Icons beziehen sich auf das [Carbon Iconset](https://carbondesignsystem.com/elements/icons/library/) von IBM.

  footer:
    label: Footer
    icon: grid-bottom
    sections:
      footerSection:
        type: fields
        fields:
          social:
            label: Footer Social Media Icons
            type: structure
            required: false
            fields:
              platform:
                label: Plattform
                type: select
                options:
                  instagram: Instagram
                  twitter: Twitter
                  x: X
                  youtube: YouTube
                  gitlab: GitLab
                  linkedin: LinkedIn
                  mastodon: Mastodon
                  facebook: Facebook
                  xing: Xing
                  github: GitHub
                  website: Website
                  email: E-Mail
                required: true
              target:
                label: URL
                type: url
                required: true

          supportedBy:
            label: Footer Logos
            type: structure
            fields:
              img:
                label: Bild
                type: files
                required: true
                multiple: false
                uploads: footer-supportedby
              alt:
                label: Alt Text
                type: text
                required: false
              href:
                label: Linkziel
                type: url
                required: false

          policyLinks:
            label: Footer Policy Links
            type: structure
            fields:
              title:
                label: Titel
                type: text
                required: true
              href:
                label: Linkziel
                type: pages
                required: true
                multiple: false
                max: 3

          bottomLine:
            label: Footer Abschlusszeile
            type: text
            help: Der Inhalt dieses Felds wird ganz am Ende jeder Seite angezeigt und kann z.B. für Copyright-Hinweise genutzt werden.

