name: Live Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  
# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: cscp-hosteurope
    steps:
      - name: Checkout repository using git
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install Node dependencies
        run: npm ci
      - name: Build site Frontend
        run: npm run build
      - name: Setup Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
          args: "--ignore-platform-reqs --optimize-autoloader"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment
          retention-days: 5
          path: |
            build/
            site/
            vendor/
            kirby/
            index.php
            .htaccess
          include-hidden-files: true

  deploy:
    needs: build
    environment: cscp-hosteurope
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment
          path: dist
      - name: Incremental sync via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftps
          local-dir: dist/
          server-dir: ${{ secrets.FTPS_FOLDER }}
          server: ${{ secrets.FTPS_HOST }}
          username: ${{ secrets.FTPS_USER }}
          password: ${{ secrets.FTPS_PASSWORD }}